### ISSUE TITLE
To-Do's before running the experiment on LeaseWeb

### ISSUE THREAD

**Issue by MaChengxin** [MaChengxin/expBT#1]
- [x] Change torrents to magnet links (https://github.com/MaChengxin/expBT/issues/2)
- [x] Make sure exactly one piece of a torrent is downloaded (https://github.com/arvidn/libtorrent/issues/1973)
- [x] Figure out what statistics are important and what are not
- [x] Try to ask the tracker for the total number of seeders and leechers (also the currently connected ones. [reference](http://www.libtorrent.org/reference-Core.html#torrent_status))(https://github.com/MaChengxin/expBT/issues/3)

**Comment by MaChengxin** [comment]
Statistics that are relevant to the swarm size are considered as "important" ones.

**Comment by MaChengxin** [comment]
Try to visualize `ses_num_incoming_piece` and `ses_num_outgoing_piece`.

**Comment by MaChengxin** [comment]
For most of the torrents, `ses_num_piece_passed` is 1 (expected), but there are a few exceptions, as shown in the following graph.
![figure_1](https://cloud.githubusercontent.com/assets/7589678/25853308/a8b563cc-34cc-11e7-8652-3f4dc871df1f.png)

**Comment by MaChengxin** [comment]
LeaseWeb login is set up:
`ssh chengxin@95.211.155.142`

**Comment by MaChengxin** [comment]
[Measurement and enhancement of BitTorrent-based video file swarming](http://www.thucsnet.org/uploads/2/5/2/8/25289795/measurement_and_enhancement_of_bittorrent-based_video_file_swarming.pdf) indicates that it measures the swarm size by asking the tracker: 

> 2,804 unavailable swarms due to the tracker failure

This paper might be helpful for the video-on-demand swarm size analysis.
